INSERT INTO comment (post_Id, username, body, created_on)
    VALUES  (1, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (1, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (1, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (1, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (1, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (1, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (1, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (1, 'user1', 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Modi possimus nobis neque dolore minus unde nihil, eos accusamus ea perferendis, at aut, deserunt quis expedita in esse? Doloremque, vitae voluptates? hi!', CURRENT_TIMESTAMP),
            (2, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (2, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (2, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (2, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (3, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (3, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (3, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (3, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (3, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (3, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (3, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (4, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (4, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (4, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (4, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (4, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (4, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (5, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (5, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (5, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (5, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (5, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (5, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (5, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (5, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (6, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (6, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (6, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (6, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (6, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (6, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (6, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (6, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (7, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (7, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (7, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (7, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (7, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (7, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (7, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (7, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (8, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (8, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (8, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (8, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (8, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (8, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (8, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (8, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (9, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (9, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (9, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (9, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (9, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (9, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (9, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (9, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (10, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (10, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (10, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (10, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (10, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (10, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (10, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (10, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (11, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (11, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (11, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (11, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (11, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (11, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (11, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (11, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (12, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (12, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (12, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (12, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (12, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (12, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (12, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (12, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (13, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (13, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (13, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (13, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (13, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (13, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (13, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (13, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (14, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (14, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (14, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (14, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (14, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (14, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (14, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (14, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (15, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (15, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (15, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (15, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (15, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (15, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (15, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (15, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (16, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (16, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (16, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (16, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (16, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (16, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (16, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (16, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (16, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (17, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (17, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (17, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (17, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (17, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (17, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (17, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (17, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (18, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (18, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (18, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (18, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (18, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (18, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (18, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (18, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (19, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (19, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (19, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (19, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (19, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (19, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (19, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (19, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (20, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (20, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (20, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (20, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (20, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (20, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (20, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (20, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (21, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (21, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (21, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (21, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (21, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (21, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (21, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (21, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP),
            (22, 'user2', 'Brilliant, amazing. I love that pic!', CURRENT_TIMESTAMP),
            (22, 'Jiwon', 'I wonder if its made of Sandworm', CURRENT_TIMESTAMP),
            (22, 'Jay', 'Awseome!', CURRENT_TIMESTAMP),
            (22, 'jsks5699', 'What is this?', CURRENT_TIMESTAMP),
            (22, 'jshim0209', 'Like!', CURRENT_TIMESTAMP),
            (22, 'devOps', 'Cool', CURRENT_TIMESTAMP),
            (22, 'user1', 'Amazing, wow, great, how cool. You sir, are a genius! Keep on posting my good man!', CURRENT_TIMESTAMP),
            (22, 'king', 'Muaddib was known among them', CURRENT_TIMESTAMP);
